// Beautiful Latin Melodic Composition
// Generated by Strudel Agent Swarm
// Duration: 1 minute | Tempo: 120 BPM | Style: Modern Latin

// === TEMPO SETTING ===
setcps(120/60/4)

// === RHYTHM FOUNDATION (by strudel-rhythm-architect) ===
// Latin clave pattern - the heartbeat
const clave = s("cp cp ~ cp ~ ~ cp ~").struct("1 1 0 1 0 0 1 0").gain(0.6)

// Conga pattern with velocity variations
const congas = s("conga:0 ~ conga:1 conga:2").gain(0.8)
  .velocity(sine.range(0.6, 0.9).slow(2))

// Bongo accents
const bongos = s("bongo:0 bongo:1").sometimes(x => x.speed(1.5))

// Shaker for continuous motion
const shaker = s("shaker*8").gain(0.3).pan(sine.range(-0.3, 0.3).slow(4))

// Supporting kick and rimshot
const kick = s("bd ~ ~ bd ~ ~ ~ ~").gain(0.7)
const rimshot = s("~ rim ~ rim").hpf(3000).gain(0.6)

// === MELODIC CONTENT (by strudel-melody-weaver) ===
// Main melody with Latin phrasing
const melody = note("a4 ~ g4 f4 e4 ~ d4 c4 b3 ~ a3 ~")
  .scale("A:harmonic_minor")
  .legato(0.9)
  .vib(4).vibmod(0.2)
  .s("sawtooth")
  .attack(0.02).decay(0.1).sustain(0.7).release(0.3)
  .lpf(2000).lpq(2)
  .gain(0.7)
  .rarely(x => x.slide(0.1))

// Harmonic progression
const harmony = chord("<Am Dm/F E7 Am> <F C/E Dm E7>")
  .voicing()
  .slow(2)
  .s("piano")
  .velocity(0.7)
  .room(0.3)

// Bass line
const bass = note("<a2 a2 d2 d2 e2 e2 a2 a2>")
  .s("sawtooth")
  .lpf(800)
  .gain(0.6)

// Counter melody for B section
const counter = note("~ e5 ~ f5 e5 d5 ~ c5")
  .scale("A:harmonic_minor")
  .delay(0.3).delaytime(0.125)
  .gain(0.4)
  .s("sawtooth")
  .attack(0.02).decay(0.1).sustain(0.7).release(0.3)
  .lpf(2000).lpq(2)

// === ATMOSPHERIC ELEMENTS (by strudel-synth-designer) ===
// Warm pad
const pad = note("<a3 c4 e4>")
  .s("square")
  .attack(0.5).release(1)
  .lpf(600).gain(0.3)
  .room(0.7)

// String section
const strings = note("<a3 c4 e4 g4>").slow(4)
  .s("triangle")
  .attack(0.3).release(0.5)
  .gain(0.4).pan(-0.3)

// === SONG STRUCTURE (by strudel-structure-composer) ===
// Intro (4 cycles) - Gentle percussion entrada
const intro = stack(
  clave,
  shaker,
  congas.gain(0.4)
).slow(1)

// A Section (8 cycles) - Main theme
const sectionA = stack(
  clave,
  congas,
  bongos,
  shaker,
  kick,
  melody,
  bass,
  harmony
).orbit(1)

// B Section (8 cycles) - Montuno contrast
const sectionB = stack(
  clave.fast(2),
  congas.fast(1.5),
  bongos,
  shaker,
  rimshot,
  counter,
  bass.fast(2),
  harmony,
  pad
).every(4, x => x.fast(2))

// === VARIATIONS (by strudel-pattern-transformer) ===
const sectionA_varied = sectionA
  .sometimes(x => x.add(note('0,7')))
  .sometimesBy(0.3, x => x.gain(0.7))

// Finale with full arrangement
const finale = stack(
  sectionA,
  strings,
  pad
).gain(1.1)
  .every(8, x => x.scramble(4))

// === FINAL MIX (by strudel-effects-engineer) ===
// Complete composition assembly
const composition = cat([
  intro,
  sectionA,
  sectionA_varied,
  sectionB,
  finale
])
.room(0.4).size(0.7)
.hpf(80).lpf(12000)
.gain(0.85)

// Play the composition
composition